name: bmad-product-leadership
version: 1.0.0
short-title: Product Leadership Advisory
description: >-
  A comprehensive expansion pack for product leadership teams that combines proven
  Silicon Valley Product Group (SVPG) methodologies with specialized roles for
  building and scaling product capabilities. This pack covers the complete product
  lifecycle from 0-1 development and product-market fit through platform transitions
  and graceful product sunsetting. Includes product coaches, exploration leads,
  fractional advisors, growth specialists, operations leads, platform leaders,
  0-1 builders, and sunset specialists - all designed to help organizations develop
  senior-level product capabilities with cross-functional collaboration expertise.
author: BMAD Product Leadership Team
slashPrefix: bmadProduct